language: node_js
node_js:
  - 9.4.0

cache:
  npm: false

script:
 - zip -r HouseHunterBE.zip dist .env package.json package-lock.json pm2.yaml .npmrc

deploy:
  verbose: true
  skip_cleanup: true
  provider: elasticbeanstalk
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
  region: "us-east-1"
  app: "HouseHunterBE"
  env: "Househunterbe-env"
  bucket_name: "househunterbe"
  zip_file: "HouseHunterBE.zip"
